### ISSUE TITLE
Invalid Syntax Error

### ISSUE THREAD

**Issue by radiantone** [jfilter/text-classification-keras#7]
File "/data/xxxx/anaconda2/lib/python2.7/site-packages/texcla/experiment.py", line 69
    history = model.fit(**fit_args, epochs=epochs,
                                  ^
SyntaxError: invalid syntax

**Comment by radiantone** [comment]
For some reason, I'm getting syntax errors in  a lot of your files. Does this package work with python 2.7?

  File "/data/xxxx/anaconda2/lib/python2.7/site-packages/texcla/libs/fastTextWikiTokenizer/tokenize.py", line 39
    ['sed', *commands], input=s.encode()).decode("utf-8")
            ^
SyntaxError: invalid syntax

**Comment by jfilter** [comment]
Should work now in 0.1.2. Let me know if you have problems with Python 2.7.
