### ISSUE TITLE
How to add tensorboard callbacks

### ISSUE THREAD

**Issue by radiantone** [jfilter/text-classification-keras#9]
Hi,
  How would you add tensorboard callbacks for visualizing the model?

**Comment by jfilter** [comment]
`experimen.train` is a wrapper around Keras' `fit`. So you should be able to pass the Tensboard callback to `train`. Something like:

```python
tbCallBack = keras.callbacks.TensorBoard(log_dir='./Graph', histogram_freq=0, write_graph=True, write_images=True)
...
experiment.train(...inputs and parameters..., callbacks=[tbCallBack])
```

See also: https://stackoverflow.com/a/42112935/4028896
